/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/University/AL_Proj/CMOS_SDR/UDP_EG4_6.2/prj/UDP_EXAMPLE/al_ip/PLL_HDMI_CLK.v
 ** Date	:	2025 09 16
 ** TD version	:	6.2.168116
************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:                50.000000MHz
//	Clock multiplication factor: 5
//	Clock division factor:       4
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 62.500000 MHZ	| 0.0000  DEG  
//		C1        	| 312.500000MHZ	| 0.0000  DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module PLL_HDMI_CLK (
  refclk,
  reset,
  extlock,
  clk0_out,
  clk1_out 
);

  input refclk;
  input reset;
  output extlock;
  output clk0_out;
  output clk1_out;

  wire clk0_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC0_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(0),
    .ICP_CURRENT(9),
    .KVCO(2),
    .LPF_CAPACITOR(2),
    .LPF_RESISTOR(8),
    .REFCLK_DIV(4),
    .FBCLK_DIV(5),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(15),
    .CLKC0_CPHASE(14),
    .CLKC0_FPHASE(0),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(3),
    .CLKC1_CPHASE(2),
    .CLKC1_FPHASE(0) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(extlock),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(PLL_HDMI_CLK_open0),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({PLL_HDMI_CLK_open8, PLL_HDMI_CLK_open7, PLL_HDMI_CLK_open6, PLL_HDMI_CLK_open5, PLL_HDMI_CLK_open4, PLL_HDMI_CLK_open3, PLL_HDMI_CLK_open2, PLL_HDMI_CLK_open1}),
    .fbclk(clk0_out),
    .clkc({PLL_HDMI_CLK_open11, PLL_HDMI_CLK_open10, PLL_HDMI_CLK_open9, clk1_out, clk0_buf}) 
  );

endmodule

